### ISSUE TITLE
ZodiacGX configuration

### ISSUE THREAD

**Issue by GinesGarcia** [NorthboundNetworks/ZodiacGX#5]
Hi,
I've trying to configure one of the port as control port by removing it from the ovs bridge. After assigning an IP (to the port already removed from ovs), I cannot reach it. Is there any way of doing this?

Regards,
Ginés.

**Comment by pzanna** [comment]
Hi Ginés,

You can reset the device back to default settings to get access again. There is information in [this thread](https://github.com/faucetsdn/faucet/issues/2349) that should help, otherwise please send me an email directly (support@northboundnetworks.com) and we can work through it.

Regards,
Paul
